-- ===========================================================================
--  SAMPLE QUESTIONS — AI-drafted (origin='ai'), for local development only.
--
--  Published here so quizzes work end to end on a dev machine. They have NOT
--  been through the independent verification the blueprint (v2.0) requires
--  before an AI question reaches a student. A teacher must review them before
--  any of these is loaded into production.
--
--  50 questions: Fractions topics 6.1-6.3 (10 each), Decimal Fractions (10),
--  Percentage (10). Each set is exactly 5 easy / 3 medium / 2 hard.
-- ===========================================================================
SET NAMES utf8mb4;

INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'easy', '3/7 ভগ্নাংশটির লব কত?', 'ভগ্নাংশের উপরের সংখ্যাকে লব বলে। 3/7 এর লব 3।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '3', 1), (@q, 'B', '7', 0), (@q, 'C', '10', 0), (@q, 'D', '4', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'easy', '5/9 ভগ্নাংশটির হর কত?', 'ভগ্নাংশের নিচের সংখ্যাকে হর বলে। 5/9 এর হর 9।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '5', 0), (@q, 'B', '9', 1), (@q, 'C', '14', 0), (@q, 'D', '4', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'easy', 'একটি কেককে সমান 8 ভাগ করে 3 ভাগ খাওয়া হলো। কেকের কত অংশ খাওয়া হলো?', 'মোট সমান ভাগ 8টি (হর), খাওয়া হয়েছে 3টি (লব)। তাই খাওয়া অংশ 3/8।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '3/8', 1), (@q, 'B', '5/8', 0), (@q, 'C', '8/3', 0), (@q, 'D', '3/5', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'easy', 'নিচের কোনটি প্রকৃত ভগ্নাংশ?', 'যে ভগ্নাংশের লব হরের চেয়ে ছোট, তা প্রকৃত ভগ্নাংশ। 4/9 এ 4 < 9।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '7/5', 0), (@q, 'B', '9/4', 0), (@q, 'C', '4/9', 1), (@q, 'D', '6/6', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'easy', 'নিচের কোনটি অপ্রকৃত ভগ্নাংশ?', 'যে ভগ্নাংশের লব হরের চেয়ে বড়, তা অপ্রকৃত ভগ্নাংশ। 9/7 এ 9 > 7।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2/3', 0), (@q, 'B', '5/8', 0), (@q, 'C', '1/4', 0), (@q, 'D', '9/7', 1);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'medium', 'একটি শ্রেণিতে 30 জন শিক্ষার্থীর মধ্যে 12 জন মেয়ে। মেয়েরা মোট শিক্ষার্থীর কত অংশ?', 'মেয়েরা 12/30 অংশ। লব ও হরকে 6 দিয়ে ভাগ করলে 12/30 = 2/5।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2/5', 1), (@q, 'B', '3/5', 0), (@q, 'C', '5/2', 0), (@q, 'D', '12/18', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'medium', '24 এর 3/8 অংশ কত?', '24 × 3/8 = 72/8 = 9।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '8', 0), (@q, 'B', '9', 1), (@q, 'C', '12', 0), (@q, 'D', '3', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'medium', '15 মিনিট 1 ঘণ্টার কত অংশ?', '1 ঘণ্টা = 60 মিনিট। 15/60 = 1/4।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '1/4', 1), (@q, 'B', '1/15', 0), (@q, 'C', '1/6', 0), (@q, 'D', '4/1', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'hard', '60 পৃষ্ঠার একটি বইয়ের প্রথম দিন 1/4 অংশ এবং দ্বিতীয় দিন 1/3 অংশ পড়া হলো। কত পৃষ্ঠা বাকি রইল?', 'প্রথম দিন 60 × 1/4 = 15 পৃষ্ঠা, দ্বিতীয় দিন 60 × 1/3 = 20 পৃষ্ঠা। মোট পড়া 35 পৃষ্ঠা। বাকি 60 − 35 = 25 পৃষ্ঠা।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '25', 1), (@q, 'B', '35', 0), (@q, 'C', '20', 0), (@q, 'D', '15', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.1'), 'hard', 'কোন সংখ্যার 2/5 অংশ 18?', 'সংখ্যাটির 2/5 অংশ = 18 হলে, 1/5 অংশ = 9, তাই পুরো সংখ্যা = 9 × 5 = 45।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '36', 0), (@q, 'B', '45', 1), (@q, 'C', '90', 0), (@q, 'D', '40', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'easy', '1/2 এর সমমান ভগ্নাংশ কোনটি?', '1/2 এর লব ও হরকে 2 দিয়ে গুণ করলে পাই 2/4।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2/4', 1), (@q, 'B', '2/3', 0), (@q, 'C', '1/4', 0), (@q, 'D', '3/4', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'easy', '3/5 এর সমমান ভগ্নাংশ কোনটি?', '3/5 এর লব ও হরকে 2 দিয়ে গুণ করলে পাই 6/10।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '6/10', 1), (@q, 'B', '6/15', 0), (@q, 'C', '5/3', 0), (@q, 'D', '9/10', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'easy', '2/3 = ?/9 — প্রশ্নবোধক চিহ্নের স্থানে কোন সংখ্যা বসবে?', 'হর 3 থেকে 9 করতে 3 দিয়ে গুণ করতে হয়। লবকেও 3 দিয়ে গুণ: 2 × 3 = 6।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '4', 0), (@q, 'B', '6', 1), (@q, 'C', '3', 0), (@q, 'D', '5', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'easy', '4/8 কে লঘিষ্ঠ আকারে প্রকাশ করলে কত হয়?', '4 ও 8 এর গসাগু 4। লব ও হরকে 4 দিয়ে ভাগ করলে পাই 1/2।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '1/2', 1), (@q, 'B', '2/4', 0), (@q, 'C', '1/4', 0), (@q, 'D', '2/8', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'easy', 'নিচের কোন জোড়া সমমান ভগ্নাংশ?', '1/3 এর লব ও হরকে 2 দিয়ে গুণ করলে 2/6 হয়। তাই 1/3 ও 2/6 সমমান।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '1/3 ও 2/6', 1), (@q, 'B', '1/3 ও 3/1', 0), (@q, 'C', '2/5 ও 5/2', 0), (@q, 'D', '3/4 ও 4/5', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'medium', '18/24 এর লঘিষ্ঠ আকার কোনটি?', '18 ও 24 এর গসাগু 6। 18 ÷ 6 = 3, 24 ÷ 6 = 4। তাই লঘিষ্ঠ আকার 3/4।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '9/12', 0), (@q, 'B', '3/4', 1), (@q, 'C', '6/8', 0), (@q, 'D', '2/3', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'medium', '5/7 = 20/? — প্রশ্নবোধক চিহ্নের স্থানে কোন সংখ্যা বসবে?', 'লব 5 থেকে 20 করতে 4 দিয়ে গুণ করা হয়েছে। হরকেও 4 দিয়ে গুণ: 7 × 4 = 28।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '25', 0), (@q, 'B', '28', 1), (@q, 'C', '21', 0), (@q, 'D', '35', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'medium', 'নিচের কোনটি 6/9 এর সমমান নয়?', '6/9 = 2/3। 4/6 = 2/3 এবং 12/18 = 2/3, কিন্তু 3/6 = 1/2।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2/3', 0), (@q, 'B', '4/6', 0), (@q, 'C', '12/18', 0), (@q, 'D', '3/6', 1);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'hard', '5/12 এর সমমান একটি ভগ্নাংশের হর 36। ভগ্নাংশটির লব কত?', '12 থেকে 36 করতে 3 দিয়ে গুণ করা হয়েছে। লব = 5 × 3 = 15।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '12', 0), (@q, 'B', '15', 1), (@q, 'C', '20', 0), (@q, 'D', '30', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.2'), 'hard', '3/4 এর সমমান একটি ভগ্নাংশের লব ও হরের যোগফল 28। ভগ্নাংশটি কত?', 'সমমান ভগ্নাংশ 3k/4k, যোগফল 7k = 28, তাই k = 4। ভগ্নাংশ = 12/16।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '12/16', 1), (@q, 'B', '9/12', 0), (@q, 'C', '15/20', 0), (@q, 'D', '6/8', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'easy', '3/7 ও 5/7 এর মধ্যে কোনটি বড়?', 'হর সমান হলে যার লব বড়, সেই ভগ্নাংশ বড়। 5 > 3, তাই 5/7 বড়।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '3/7', 0), (@q, 'B', '5/7', 1), (@q, 'C', 'দুটি সমান', 0), (@q, 'D', 'বলা যায় না', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'easy', '1/3 ও 1/5 এর মধ্যে কোনটি ছোট?', 'লব সমান হলে যার হর বড়, সেই ভগ্নাংশ ছোট। 5 > 3, তাই 1/5 ছোট।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '1/3', 0), (@q, 'B', '1/5', 1), (@q, 'C', 'দুটি সমান', 0), (@q, 'D', 'বলা যায় না', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'easy', '2/9, 7/9, 4/9, 5/9 এর মধ্যে বৃহত্তম কোনটি?', 'সবগুলোর হর 9। যার লব সবচেয়ে বড় (7), সেটিই বৃহত্তম: 7/9।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2/9', 0), (@q, 'B', '7/9', 1), (@q, 'C', '4/9', 0), (@q, 'D', '5/9', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'easy', 'সমান হরবিশিষ্ট দুটি ভগ্নাংশের মধ্যে যার লব বড়, সেটি —', 'হর সমান থাকলে সমান মাপের ভাগ গোনা হয়। বেশি ভাগ মানে বড় ভগ্নাংশ।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', 'বড়', 1), (@q, 'B', 'ছোট', 0), (@q, 'C', 'সমান', 0), (@q, 'D', 'অপ্রকৃত', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'easy', '1/2 ও 2/4 এর মধ্যে সম্পর্ক কী?', '2/4 এর লব ও হরকে 2 দিয়ে ভাগ করলে 1/2 হয়। তাই দুটি সমান।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '1/2 বড়', 0), (@q, 'B', '2/4 বড়', 0), (@q, 'C', 'দুটি সমান', 1), (@q, 'D', 'তুলনা করা যায় না', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'medium', 'নিচের ভগ্নাংশগুলোর মধ্যে কোনটি বৃহত্তম?', 'হরগুলোর লসাগু 24। 3/4 = 18/24, 5/8 = 15/24, 2/3 = 16/24, 7/12 = 14/24। বৃহত্তম 18/24 = 3/4।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '3/4', 1), (@q, 'B', '5/8', 0), (@q, 'C', '2/3', 0), (@q, 'D', '7/12', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'medium', '2/3 ও 3/5 এর মধ্যে কোনটি বড়?', 'হর সমান করি: 2/3 = 10/15, 3/5 = 9/15। 10 > 9, তাই 2/3 বড়।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2/3', 1), (@q, 'B', '3/5', 0), (@q, 'C', 'দুটি সমান', 0), (@q, 'D', 'বলা যায় না', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'medium', 'ছোট থেকে বড় ক্রমে সাজাও: 1/2, 1/3, 1/6', 'লব সমান, তাই যার হর বড় সে ছোট: 1/6 < 1/3 < 1/2।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '1/6, 1/3, 1/2', 1), (@q, 'B', '1/2, 1/3, 1/6', 0), (@q, 'C', '1/3, 1/6, 1/2', 0), (@q, 'D', '1/6, 1/2, 1/3', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'hard', 'নিচের কোন ভগ্নাংশটি 1/2 এর চেয়ে বড় কিন্তু 3/4 এর চেয়ে ছোট?', 'হর 8 করি: 1/2 = 4/8, 3/4 = 6/8। 4/8 ও 6/8 এর মাঝে আছে 5/8।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2/5', 0), (@q, 'B', '5/8', 1), (@q, 'C', '7/8', 0), (@q, 'D', '1/4', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (6, (SELECT id FROM topics WHERE chapter_id=6 AND code='6.3'), 'hard', 'রাফি একটি কাজের 3/8 অংশ এবং নুসরাত 2/5 অংশ শেষ করল। কে বেশি কাজ করেছে এবং কত অংশ বেশি?', 'হর 40 করি: 3/8 = 15/40, 2/5 = 16/40। নুসরাত বেশি করেছে, 16/40 − 15/40 = 1/40 অংশ।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', 'নুসরাত, 1/40 অংশ বেশি', 1), (@q, 'B', 'রাফি, 1/40 অংশ বেশি', 0), (@q, 'C', 'নুসরাত, 1/13 অংশ বেশি', 0), (@q, 'D', 'দুজন সমান', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'easy', '0.7 কে সাধারণ ভগ্নাংশে প্রকাশ করলে কত হয়?', 'দশমিকের পর একটি অঙ্ক মানে দশমাংশ। 0.7 = 7/10।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '7/10', 1), (@q, 'B', '7/100', 0), (@q, 'C', '1/7', 0), (@q, 'D', '70/10', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'easy', '3/100 কে দশমিকে প্রকাশ করলে কত হয়?', 'শতাংশ মানে দশমিকের পর দুই ঘর। 3/100 = 0.03।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '0.3', 0), (@q, 'B', '0.03', 1), (@q, 'C', '3.00', 0), (@q, 'D', '0.003', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'easy', '2.45 সংখ্যাটিতে 4 অঙ্কটির স্থানীয় মান কত?', 'দশমিকের ঠিক পরের ঘর দশমাংশের ঘর। তাই 4 এর স্থানীয় মান 4/10 = 0.4।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '4', 0), (@q, 'B', '0.4', 1), (@q, 'C', '0.04', 0), (@q, 'D', '40', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'easy', '0.5 + 0.3 = কত?', 'দশমাংশের ঘরে 5 + 3 = 8। তাই 0.5 + 0.3 = 0.8।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '0.8', 1), (@q, 'B', '0.08', 0), (@q, 'C', '8', 0), (@q, 'D', '0.53', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'easy', 'নিচের কোনটি বৃহত্তম?', 'দশমাংশের ঘর তুলনা করি: 0.5 এ 5, অন্যগুলোতে 0, 4, 4। তাই 0.5 বৃহত্তম।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '0.5', 1), (@q, 'B', '0.05', 0), (@q, 'C', '0.45', 0), (@q, 'D', '0.405', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'medium', '4.6 − 1.75 = কত?', '4.6 কে 4.60 লিখি। 4.60 − 1.75 = 2.85।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2.85', 1), (@q, 'B', '3.15', 0), (@q, 'C', '2.95', 0), (@q, 'D', '3.85', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'medium', '0.25 × 4 = কত?', '25 × 4 = 100। গুণ্যে দশমিকের পর দুই অঙ্ক, তাই 1.00 = 1।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '0.1', 0), (@q, 'B', '1', 1), (@q, 'C', '10', 0), (@q, 'D', '0.01', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'medium', '3.6 ÷ 0.4 = কত?', 'ভাজ্য ও ভাজক দুটিকেই 10 দিয়ে গুণ করি: 36 ÷ 4 = 9।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '0.9', 0), (@q, 'B', '9', 1), (@q, 'C', '90', 0), (@q, 'D', '1.44', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'hard', 'একটি কলমের দাম 12.50 টাকা। এরকম 6টি কলমের দাম কত টাকা?', '12.50 × 6 = 75.00 টাকা।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '72.50', 0), (@q, 'B', '75.00', 1), (@q, 'C', '62.50', 0), (@q, 'D', '80.00', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (7, (SELECT id FROM topics WHERE chapter_id=7 AND code='7.1'), 'hard', '5.4 মিটার লম্বা একটি ফিতাকে সমান 6 টুকরা করলে প্রতি টুকরার দৈর্ঘ্য কত মিটার?', '5.4 ÷ 6 = 0.9 মিটার।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — দশমিক ভগ্নাংশ', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '0.9', 1), (@q, 'B', '9', 0), (@q, 'C', '0.09', 0), (@q, 'D', '1.1', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'easy', '50% কে সাধারণ ভগ্নাংশে প্রকাশ করলে কত হয়?', '50% = 50/100 = 1/2।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '1/2', 1), (@q, 'B', '1/5', 0), (@q, 'C', '1/50', 0), (@q, 'D', '2/1', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'easy', '1/4 কে শতকরায় প্রকাশ করলে কত হয়?', '1/4 × 100% = 25%।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '4%', 0), (@q, 'B', '25%', 1), (@q, 'C', '40%', 0), (@q, 'D', '14%', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'easy', '0.35 = শতকরা কত?', '0.35 × 100% = 35%।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '3.5%', 0), (@q, 'B', '35%', 1), (@q, 'C', '350%', 0), (@q, 'D', '0.35%', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'easy', '200 এর 10% কত?', '200 × 10/100 = 20।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '2', 0), (@q, 'B', '20', 1), (@q, 'C', '10', 0), (@q, 'D', '210', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'easy', '"শতকরা" কথাটির অর্থ কী?', 'শতকরা মানে প্রতি একশ (100) এর মধ্যে কত।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', 'প্রতি একশতে', 1), (@q, 'B', 'প্রতি দশে', 0), (@q, 'C', 'প্রতি হাজারে', 0), (@q, 'D', 'প্রতি একে', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'medium', 'একটি পরীক্ষায় 40টি প্রশ্নের মধ্যে রিয়া 30টির সঠিক উত্তর দিল। সে শতকরা কত ভাগ প্রশ্নের সঠিক উত্তর দিয়েছে?', '30/40 × 100% = 75%।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '30%', 0), (@q, 'B', '70%', 0), (@q, 'C', '75%', 1), (@q, 'D', '80%', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'medium', '500 টাকার 12% কত টাকা?', '500 × 12/100 = 60 টাকা।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '50', 0), (@q, 'B', '60', 1), (@q, 'C', '12', 0), (@q, 'D', '120', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'medium', 'কোন সংখ্যার 20% = 30?', 'সংখ্যাটির 20/100 অংশ = 30, তাই সংখ্যা = 30 × 100/20 = 150।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '6', 0), (@q, 'B', '60', 0), (@q, 'C', '150', 1), (@q, 'D', '600', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'hard', 'একটি জামার দাম 800 টাকা। 15% ছাড়ে কিনলে কত টাকা দিতে হবে?', 'ছাড় = 800 × 15/100 = 120 টাকা। দিতে হবে 800 − 120 = 680 টাকা।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '680', 1), (@q, 'B', '785', 0), (@q, 'C', '120', 0), (@q, 'D', '700', 0);
INSERT INTO questions (chapter_id, topic_id, difficulty, stem, explanation, source_ref, origin, status) VALUES (8, (SELECT id FROM topics WHERE chapter_id=8 AND code='8.1'), 'hard', 'একটি বিদ্যালয়ের 600 জন শিক্ষার্থীর 45% ছেলে। মেয়ে কতজন?', 'ছেলে = 600 × 45/100 = 270 জন। মেয়ে = 600 − 270 = 330 জন।', 'NCTB প্রাথমিক গণিত, পঞ্চম শ্রেণি — শতকরা', 'ai', 'published');
SET @q = LAST_INSERT_ID();
INSERT INTO question_options (question_id, label, body, is_correct) VALUES (@q, 'A', '270', 0), (@q, 'B', '330', 1), (@q, 'C', '300', 0), (@q, 'D', '355', 0);
